-- ============================================================
-- BCS-One: কোর্স ভিডিও টেবিল (YouTube ইম্বেড লাইব্রেরি)
-- Supabase Dashboard → SQL Editor → এই ফাইলটা পেস্ট করে Run করুন
-- ============================================================

create table if not exists public.course_videos (
  id          bigint generated by default as identity primary key,
  course      text not null,                -- কোন কোর্সের (যেমন: সাধারণ কোর্স / বাংলা ব্যাচ)
  subject     text,                         -- বিষয় (যেমন: বাংলা সাহিত্য) — খালি রাখলে "সাধারণ"
  title       text not null,                -- ভিডিওর নাম
  youtube_id  text not null,                -- YouTube ভিডিও ID (পুরো URL দিলেও অ্যাপ নিজে বের করে নেয়)
  description text,
  sort_order  int not null default 0,       -- সাজানোর ক্রম (ছোট = আগে)
  created_at  timestamptz not null default now()
);

-- সার্ভার-সাইড (service role) ছাড়া কেউ পড়তে/লিখতে পারবে না
alter table public.course_videos enable row level security;

-- স্টুডেন্ট/অ্যানন-ক্লায়েন্ট সরাসরি পড়তে পারবে না — সব রিকোয়েস্ট সার্ভার অ্যাকশনের
-- মাধ্যমে যায় (service role key RLS বাইপাস করে), তাই পলিসি লাগবে না।
