-- ============================================================================
--  BCS-One — একবারে চালানোর নিরাপদ সেটআপ স্ক্রিপ্ট
--  Supabase Dashboard → SQL Editor → এই পুরো ফাইল পেস্ট করে Run করুন।
--
--  কেন একটি ফাইল: আগে আলাদা আলাদা মাইগ্রেশন ফাইল চালাতে হতো, আর কোনো টেবিল না
--  থাকলে মাঝপথে এরর হয়ে পুরোটা রোলব্যাক হয়ে যেত। এখানে প্রতিটি নির্ভরশীল ধাপ
--  `to_regclass` দিয়ে ঘেরা — কিছু না থাকলে এরর নয়, শুধু NOTICE দেখাবে।
--
--  ✅ বারবার Run করা নিরাপদ — কিছু মোছে না, কিছু নষ্ট করে না।
--  ⚠️ শর্ত: সার্ভারে SUPABASE_SERVICE_ROLE_KEY সেট থাকতে হবে (RLS চালু হওয়ার পর
--     অ্যাপের সব ডেটা-অ্যাক্সেস ওই key দিয়েই হয়)।
--
--  এই ফাইলে যা নেই: 2025_cleanup_duplicate_live_submissions.sql — সেটিতে একটি
--  unguarded DELETE আছে, তাই ইচ্ছে করে বাদ দেওয়া হয়েছে।
-- ============================================================================


-- ============================================================================
--  ধাপ ১ — কোর্স ভিডিও লাইব্রেরি
-- ============================================================================
create table if not exists public.course_videos (
  id          bigint generated by default as identity primary key,
  course      text not null,
  subject     text,
  title       text not null,
  youtube_id  text not null,
  description text,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now()
);
alter table public.course_videos enable row level security;


-- ============================================================================
--  ধাপ ২ — কোর্সের দাম / ছাড় / বিবরণ
-- ============================================================================
create table if not exists public.course_prices (
  course         text primary key,
  price          numeric,
  offer_price    numeric,
  planned_exams  integer,
  planned_videos integer
);
alter table public.course_prices add column if not exists planned_exams  integer;
alter table public.course_prices add column if not exists planned_videos integer;
alter table public.course_prices add column if not exists description    text;
alter table public.course_prices add column if not exists details        text;


-- ============================================================================
--  ধাপ ৩ — কোর্সভেদে WhatsApp গ্রুপ লিংক
-- ============================================================================
create table if not exists public.course_whatsapp (
  course     text primary key,
  link       text not null,
  updated_at timestamptz default timezone('utc', now())
);


-- ============================================================================
--  ধাপ ৪ — দৈনিক সংবাদ
-- ============================================================================
create table if not exists public.daily_news (
  id         uuid primary key default gen_random_uuid(),
  heading    text not null,
  body       text not null,
  created_at timestamptz default timezone('utc', now())
);
create index if not exists daily_news_created_idx on public.daily_news (created_at desc);
alter table public.daily_news add column if not exists read_count integer not null default 0;

create or replace function public.increment_daily_news_read(row_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.daily_news
     set read_count = read_count + 1
   where id = row_id;
end;
$$;
revoke execute on function public.increment_daily_news_read(uuid) from anon, authenticated;
grant  execute on function public.increment_daily_news_read(uuid) to service_role;


-- ============================================================================
--  ধাপ ৫ — ভুল-উত্তরের খাতা ও বুকমার্ক
-- ============================================================================
create table if not exists public.student_mistakes (
  id          text not null,
  student_id  text not null,
  q           text not null,
  opts        jsonb not null default '[]'::jsonb,
  correct     int  not null default 0,
  exp         text not null default '',
  user_ans    int,
  exam_title  text not null default '',
  subject     text,
  topic       text,
  timestamp   text,
  created_at  timestamptz not null default now(),
  primary key (student_id, id)
);
create table if not exists public.student_bookmarks (
  id          text not null,
  student_id  text not null,
  q           text not null,
  opts        jsonb not null default '[]'::jsonb,
  correct     int  not null default 0,
  exp         text not null default '',
  user_ans    int,
  exam_title  text not null default '',
  subject     text,
  topic       text,
  timestamp   text,
  created_at  timestamptz not null default now(),
  primary key (student_id, id)
);
alter table public.student_mistakes  enable row level security;
alter table public.student_bookmarks enable row level security;


-- ============================================================================
--  ধাপ ৬ — "পড়া হয়েছে" টিকের সিঙ্ক
-- ============================================================================
create table if not exists public.student_read_questions (
  id          text not null,
  student_id  text not null,
  q           text not null,
  opts        jsonb not null default '[]'::jsonb,
  correct     int  not null default 0,
  exp         text not null default '',
  user_ans    int,
  exam_title  text not null default '',
  subject     text,
  topic       text,
  timestamp   text,
  created_at  timestamptz not null default now(),
  primary key (student_id, id)
);
create index if not exists student_read_questions_student_idx
  on public.student_read_questions (student_id, created_at desc);
alter table public.student_read_questions enable row level security;


-- ============================================================================
--  ধাপ ৭ — পরীক্ষা শুরুর রেকর্ড (লিডারবোর্ড-যোগ্যতা ও সময়-হিসাবের ভিত্তি)
--  ⚠️ এটি না থাকলে: শুরুর-সময়-ভিত্তিক লিডারবোর্ড-যোগ্যতা কাজ করে না, আর
--     elapsed time ক্লায়েন্টের পাঠানো মানে ফিরে যায়।
-- ============================================================================
create table if not exists public.exam_attempt_starts (
  id          bigint generated always as identity primary key,
  student_id  text not null,
  exam_id     text not null,
  started_at  timestamptz not null default timezone('utc', now()),
  created_at  timestamptz not null default timezone('utc', now()),
  unique (exam_id, student_id)
);
-- (আলাদা index ইচ্ছে করে বানানো হয়নি — unique constraint নিজেই index বানায়)


-- ============================================================================
--  ধাপ ৮ — নির্ভরশীল অংশ (বেস টেবিল না থাকলে চুপচাপ এড়িয়ে যাবে)
-- ============================================================================
do $$
begin
  if to_regclass('public.submissions') is not null then
    execute 'create unique index if not exists submissions_one_live_per_student
               on public.submissions (exam_key, student_id)
               where is_live_submission = true';
    raise notice 'ধাপ ৮ক: submissions লাইভ-ইউনিক index ঠিক আছে';
  else
    raise notice 'ধাপ ৮ক: SKIPPED — public.submissions টেবিল নেই';
  end if;

  if to_regclass('public.enroll_requests') is not null then
    execute 'alter table public.enroll_requests add column if not exists coupon text';
    raise notice 'ধাপ ৮খ: enroll_requests.coupon ঠিক আছে';
  else
    raise notice 'ধাপ ৮খ: SKIPPED — public.enroll_requests টেবিল নেই';
  end if;
end $$;


-- ============================================================================
--  ধাপ ৯ — 🔴 নিরাপত্তা: RLS চালু + anon/authenticated-এর লেখার অধিকার বাতিল
--
--  কেন: এই টেবিলগুলো RLS ছাড়াই তৈরি হয়েছিল, আর পুরো রেপোতে একটি policy-ও নেই।
--  RLS ছাড়া পাবলিক anon key দিয়েই (যেটা ক্লায়েন্ট বান্ডেলে থাকে) যেকেউ সারি
--  পড়তে/লিখতে/মুছতে পারে। অথচ অ্যাপের সব অ্যাক্সেস সার্ভার-অ্যাকশন দিয়ে
--  service_role-এ হয় — তাই anon-এর কোনো অধিকারই দরকার নেই।
-- ============================================================================

-- ৯ক. যেসব টেবিলে anon-এর কোনো অধিকারই থাকা উচিত নয় (শুধু service_role)
do $$
begin
  if to_regclass('public.exam_attempt_starts') is not null then
    execute 'alter table public.exam_attempt_starts enable row level security';
    execute 'revoke all on table public.exam_attempt_starts from anon, authenticated';
  else
    raise notice 'ধাপ ৯ক: exam_attempt_starts টেবিল নেই';
  end if;

  if to_regclass('public.course_whatsapp') is not null then
    execute 'alter table public.course_whatsapp enable row level security';
    execute 'revoke all on table public.course_whatsapp from anon, authenticated';
  else
    raise notice 'ধাপ ৯ক: course_whatsapp টেবিল নেই';
  end if;

  if to_regclass('public.course_videos') is not null then
    execute 'alter table public.course_videos enable row level security';
    execute 'revoke all on table public.course_videos from anon, authenticated';
  end if;

  if to_regclass('public.student_mistakes') is not null then
    execute 'alter table public.student_mistakes enable row level security';
    execute 'revoke all on table public.student_mistakes from anon, authenticated';
  end if;

  if to_regclass('public.student_bookmarks') is not null then
    execute 'alter table public.student_bookmarks enable row level security';
    execute 'revoke all on table public.student_bookmarks from anon, authenticated';
  end if;

  if to_regclass('public.student_read_questions') is not null then
    execute 'alter table public.student_read_questions enable row level security';
    execute 'revoke all on table public.student_read_questions from anon, authenticated';
  end if;
end $$;

-- ৯খ. পাবলিক তথ্য: পড়া থাকবে (SELECT policy), লেখা সম্পূর্ণ বন্ধ
do $$
begin
  if to_regclass('public.course_prices') is not null then
    execute 'alter table public.course_prices enable row level security';
    execute 'revoke insert, update, delete, truncate, references, trigger on table public.course_prices from anon, authenticated';
    execute 'drop policy if exists bcs_public_read_course_prices on public.course_prices';
    execute 'create policy bcs_public_read_course_prices on public.course_prices for select to anon, authenticated using (true)';
  else
    raise notice 'ধাপ ৯খ: course_prices টেবিল নেই';
  end if;

  if to_regclass('public.daily_news') is not null then
    execute 'alter table public.daily_news enable row level security';
    execute 'revoke insert, update, delete, truncate, references, trigger on table public.daily_news from anon, authenticated';
    execute 'drop policy if exists bcs_public_read_daily_news on public.daily_news';
    execute 'create policy bcs_public_read_daily_news on public.daily_news for select to anon, authenticated using (true)';
  else
    raise notice 'ধাপ ৯খ: daily_news টেবিল নেই';
  end if;
end $$;

-- ৯গ. অপ্রয়োজনীয় redundant index সরানো (unique constraint-ই index বানায়)
drop index if exists public.exam_attempt_starts_exam_idx;


-- ============================================================================
--  ধাপ ১০ (ঐচ্ছিক) — পুরোনো সাবমিশনের নাম রোস্টার অনুযায়ী এককালীন হালনাগাদ
--  `submissions.student_name` সাবমিটের সময় snapshot হয়; আগে নাম বদলালে
--  লিডারবোর্ডে পুরোনো নামই থেকে যেত। কিছু মোছে না — শুধু যেখানে নাম রোস্টারের
--  সাথে মিলছে না, সেখানে রোস্টারের নাম কপি হয়।
--  এই ধাপ বাদ দিতে চাইলে নিচের পুরো DO ব্লকটি মুছে দিন।
-- ============================================================================
do $$
declare
  n_before bigint := 0;
  n_after  bigint := 0;
begin
  if to_regclass('public.submissions') is null
     or to_regclass('public.allowed_students') is null then
    raise notice 'ধাপ ১০: SKIPPED — submissions বা allowed_students টেবিল নেই';
  else
    execute 'select count(*) from public.submissions s
               join public.allowed_students a on a.id = s.student_id
              where coalesce(a.name, '''') <> ''''
                and s.student_name is distinct from a.name' into n_before;

    execute 'update public.submissions s
                set student_name = a.name
               from public.allowed_students a
              where a.id = s.student_id
                and coalesce(a.name, '''') <> ''''
                and s.student_name is distinct from a.name';

    execute 'select count(*) from public.submissions s
               join public.allowed_students a on a.id = s.student_id
              where coalesce(a.name, '''') <> ''''
                and s.student_name is distinct from a.name' into n_after;

    raise notice 'ধাপ ১০: % টি সাবমিশনের নাম হালনাগাদ হয়েছে (বাকি: %)', n_before, n_after;
  end if;
end $$;


-- ============================================================================
--  ধাপ ১১ — চূড়ান্ত রিপোর্ট
-- ============================================================================

-- ১১ক. RLS অবস্থা — কোথাও rls_enabled = false থাকলে ধাপ ৯ ছাড়া কিছু ছাড়া হয়নি,
--       সেই টেবিলটি তৈরি করার পর ধাপ ৯ আবার Run করুন।
select c.relname                       as table_name,
       c.relrowsecurity                as rls_enabled,
       (select count(*) from pg_policies p
         where p.schemaname = 'public' and p.tablename = c.relname) as policy_count
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
 where n.nspname = 'public' and c.relkind = 'r'
 order by c.relrowsecurity asc, c.relname;

-- ১১খ. anon/authenticated-এর অধিকার — এখানে INSERT/UPDATE/DELETE থাকলে সমস্যা
select table_name, grantee,
       string_agg(privilege_type, ',' order by privilege_type) as privileges
  from information_schema.role_table_grants
 where table_schema = 'public' and grantee in ('anon', 'authenticated')
 group by table_name, grantee
 order by table_name, grantee;

-- ১১গ. অ্যাপের প্রত্যাশিত টেবিলগুলোর উপস্থিতি — present = null মানে টেবিল নেই
select t.name as expected_table,
       to_regclass('public.' || t.name) as present
  from (values
          ('exams'), ('exam_questions_link'), ('question_bank'), ('submissions'),
          ('allowed_students'), ('app_settings'), ('topic_questions'),
          ('enroll_requests'), ('subjects'), ('exam_questions'),
          ('course_videos'), ('course_prices'), ('course_whatsapp'), ('daily_news'),
          ('student_mistakes'), ('student_bookmarks'), ('student_read_questions'),
          ('exam_attempt_starts')
       ) as t(name)
 order by present nulls first, t.name;
